ALTER TABLE memories ADD COLUMN IF NOT EXISTS is_structured BOOLEAN DEFAULT false;
ALTER TABLE memories ADD COLUMN IF NOT EXISTS relation_label VARCHAR(100);
ALTER TABLE memories ADD COLUMN IF NOT EXISTS object_value VARCHAR(500);
ALTER TABLE memories ADD COLUMN IF NOT EXISTS graph_edge_id VARCHAR(255);
